### PR TITLE
Setup infrastructure for RTL layouts

### LINKED ISSUE #15: Setup infrastructure for RTL layouts
Currently Vocabulary has been designed only with left-to-right layouts in mind. While this is acceptable for most languages, a number of languages, notably Arabic, are written right-to-left (RTL).

Support for RTL layouts is a crucial part of internationalisation and cannot be overlooked. The goal is to incorporate support for RTL layouts into the framework integrated with Vue-i18n so as to automatically switch to RTL whenever the active locale calls for it.

### PR DESCRIPTION
**Pull request by HAMZABoxer98**
Fixes #15

**Description**
I made some changes on the `/patterns/locale.vue`. Also, I have updated its `locale.md` file. 

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by dhruvkb** [comment]
@HAMZABoxer98 this PR contains a lot of commits that are not relevant to the PR such as
- tests from PR #36 
- Popover component from PR #40
- merge commits from your own branches

Please remove these extraneous commits and send in a PR with only the commits that involve the RTL scaffolding code.

**Comment by HAMZABoxer98** [comment]
@dhruvkb , I spent 2 hours trying to delete previous commits, what should I do ? I tried pushing a new PR but I still getting these 14 commits again.

**Comment by HAMZABoxer98** [comment]
Also, when I remove the history by creating a new branch with `--orphan`, I can't make a pull request because I can't compare it...

**Comment by HAMZABoxer98** [comment]
Solved now 🤕 , but I still see a message down below:

> This branch has conflicts that must be resolved

**Comment by dhruvkb** [comment]
That error is because your PR makes changes to the `Locale` component which is also changed by another commit in the `master` branch. You'll need to pull master and rebase your branch on top of it to get rid of the conflicts.

**Comment by dhruvkb** [comment]
Congratulations @HAMZABoxer98 :tada:!

**Pull request merged**
