### PR TITLE
Adding popup component

### LINKED ISSUE #7: Addition of missing components
While Vocabulary has a sizeable collection of components now, it is still far far away from being exhaustive. There are tons of components that need to be developed and this issue will serve to keep a track of components that have been proposed and are being worked on.

This is a discussion thread that will mark all components that have been requested by the community of users.

To request a component, just open a Markdown checkbox with the name of the component. Upvotes (:+1:) and downvotes (:-1:) will determine whether the component must be developed and once developed and merged, it will be checked off.

Example request would contain something like `- [ ] Component X` which renders like
- [ ] Component X

You can and should also add some description, mock-ups or links to other libraries that provide this component.

### PR DESCRIPTION
**Pull request by HAMZABoxer98**
Partially addresses #7

**Description**

This PR is for adding a very basic Popup component with basic styles ( simplicity, color, roundness and colors inversion ).

**Other information**

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by HAMZABoxer98** [comment]
@dhruvkb , I didn't provide any unit tests yet, I think I should wait your permission. don't forget that this is a very basic component.
*Important to know*:
1- The Popup is attached automatically to its first parent, for example:
`
<Button>
  Button Component
  <Popover>This Popup is attached to that Button</Popover>
</Button>
`
That Popup is attached to that Button.

2- The Popup has two actions ( hover/ click ):
For the click action, the Popup still open till you click again to close it.

I didn't gave it any default padding, so I think the user is able to give it some styling, in this case I don't see any advantage from creating another component for a Tooltip, what do you think ?

**Comment by HAMZABoxer98** [comment]
@dhruvkb  take a look at this, I need your permission to remove the outline from buttons.
Popover

**Comment by dhruvkb** [comment]
It would be a good idea to incorporate tests for this component with the PR itself so that tests for this component do not pile on in the general backlog. Additionally, this PR too suffers from https://github.com/creativecommons/cc-vocabulary/pull/41#issuecomment-541499096 which should be resolved before merge.

**Comment by dhruvkb** [comment]
I saw the code and noticed that this component too is not following the style guide. The Standard code style should also be followed in the component. See code of existing components for reference.

**Comment by dhruvkb** [comment]
@HAMZABoxer98 the outline should be on the button, why is it also covering the popup component?

**Comment by HAMZABoxer98** [comment]
> @HAMZABoxer98 I saw the code and noticed that this component too is not following the style guide. The Standard code style should also be followed in the component. See code of existing components for reference.
More details ?

> @HAMZABoxer98 the outline should be on the button, why is it also covering the popup component?
because it's wrapped inside a button, in this case we should remove  the outline from the button.

**Comment by dhruvkb** [comment]
#Specifically I noticed that you’re using `;`. This means that code hasn’t been linted by Standard. There are many more such deviations from the rules of Standard JS.
Why is the popover ‘wrapped by’ a button? Is it a descendent of the button element?

**Comment by HAMZABoxer98** [comment]
> Why is the popover ‘wrapped by’ a button? Is it a descendent of the button element?
yes

**Comment by HAMZABoxer98** [comment]
@dhruvkb , take a look at the styleguid to see how Popover component works.

**Comment by dhruvkb** [comment]
Resolved by b08504f.

**Comment by HAMZABoxer98** [comment]
@dhruvkb , why you didn't merge this ? is there any issues with my code ?

**Comment by dhruvkb** [comment]
Yes, there were some major issues.

- Most notably, it's heavily based on the use of `ref`s and `parentElement`. Both these techniques involve direct DOM manipulation which is frowned upon in Vue. The use of `parentElement` is even more discouraged as compared to `$parent`.
- It also uses JS for styling which is another unoptimal thing because generally we assign the following roles to the codebase:
  - HTML - structure/content
  - CSS - styling
  - JS - logic/interactivity

The alternate implementation is
- simpler ("all code is technical debt" ⇒ less code is better code)
- uses Vue features such as `slots` to manage the trigger and the popup
- uses CSS features such as `transform` for positioning rather than JS calculations

If you'd like, I'll leave a detailed review on the PR showing exactly what I mean.

**Comment by HAMZABoxer98** [comment]
@dhruvkb , no need for more details, thank you for these instructions 👍

**Pull request closed without merging**
